### ISSUE TITLE
soft WDT reset

### ISSUE THREAD

**Issue by plangenhuizen** [nldroid/CustomP1UartComponent#2]
Hoi nldroid

Ik kwam jouw repository tegen toen ik aan het zoeken was naar een esphome implementatie voor een dsmr meter. Nu heb ik jouw code geflashed op mijn d1 mini, maar nu krijg ik iedere keer een soft WDT reset terwijl de d1 mini data aan het uitlezen is. Enig idee hoe ik dit kan oplossen?

**Comment by plangenhuizen** [comment]
Oke, blijkbaar een fout aan mijn zijde... na ongeveer 10 pogingen gaat het ineens wel goed. In ieder geval bedankt voor je effort die je in deze component hebt gestoken!

**Comment by nldroid** [comment]
Wat ik wel gezien heb zijn resets als de ESP nog niet aan de P1 poort hangt, Ik weet niet precies waardoor dat komt. Ik zal het toevoegen aan de readme.

**Comment by plangenhuizen** [comment]
Klopt, dat was inderdaad mijn probleem. Wat ik online kon vinden is dat de soft WDT reset een watchdog reset is. Het komt er, als ik het goed heb begrepen, op neer dat je een infinite loop (of in ieder geval een loop die te lang duurt) in je code hebt. Na een debug sessie op jouw code zag ik dat je code in de eerste loop van de read_message functie blijft hangen ( while(!footerfound) ) als de ESP nog niet aan de P1 poort hangt. Wellicht dat je hier wat mee kunt.

________________________________
Van: nldroid <notifications@github.com>
Verzonden: donderdag 2 januari 2020 16:52
Aan: nldroid/CustomP1UartComponent <CustomP1UartComponent@noreply.github.com>
CC: plangenhuizen <patricklangenhuizen@hotmail.com>; State change <state_change@noreply.github.com>
Onderwerp: Re: [nldroid/CustomP1UartComponent] soft WDT reset (#2)


Wat ik wel gezien heb zijn resets als de ESP nog niet aan de P1 poort hangt, Ik weet niet precies waardoor dat komt. Ik zal het toevoegen aan de readme.

**Comment by nldroid** [comment]
Goed gevonden. Ik moet dus achterhalen of er überhaupt iets gelezen kan worden.

**Comment by nldroid** [comment]
Ik heb error handling toegevoegd. Hij geeft nu een melding en probeert later opnieuw om te lezen.

Dank voor het uitzoeken.

**Comment by WiebKastanje** [comment]
SUPER !
Ik ga je werk gebruiken met mijn Home Assistent om de SAGEMCOM XS210 ESMR5, die ik sinds kort heb, uit te lezen. Eerst kabeltje maken, dan met je software aan de slag.  Fantastisch begin van het nieuwe jaar.
![XS210 ESMR5](https://user-images.githubusercontent.com/46934766/71763712-4cd78980-2edf-11ea-8086-1b5787c7d14d.PNG)

**Comment by plangenhuizen** [comment]
Werkt bij mij goed op mijn sagemcom, echt super werk van nldroid!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by plangenhuizen** [comment]
Geen probleem, graag gedaan!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
