### ISSUE TITLE
nauwkeurigheid instant voltage en current sensors

### ISSUE THREAD

**Issue by plangenhuizen** [nldroid/CustomP1UartComponent#3]
Hey nldroid

Het viel mij vandaag op dat de instant current en instant voltage sensoren tot 3 decimalen nauwkeurig zijn in jouw read_p1.yaml. Ik heb dit ook in mijn .yaml file gezet, alleen krijg ik totaal geen getallen achter de komma. Ik krijg bijv het laatste uur alleen 1.000 of 2.000 ampère. Enig idee waar dit aan kan liggen? Bij de rest van de sensoren lijkt dit wel goed te gaan.

**Comment by nldroid** [comment]
Ik heb me niet verdiept in alle waarden. Ik weet dus ook niet wat er in de specificaties over staat. Ik heb overgenomen wat er in de dsmr library staat..
Als je het zeker wil weten, zou je de officiële specificaties kunnen opzoeken voor de DSMR versie van jouw meter. Het zal ongewtijfeld een pdf zijn die ergens beschikbaar is.

**Comment by plangenhuizen** [comment]
Duidelijk. Had ik inderdaad ook meteen zelf kunnen doen. De specificaties geven aan dat het in gehele getallen wordt verstuurd, dus weinig aan te veranderen. Bedankt in ieder geval voor je response

**Comment by nldroid** [comment]
Geen probleem. Ik kan het in de yaml voorbeeld aanpassen zodat het voor anderen duidelijk is. Geen idee of het in de verschillende dsmr versies anders is.
