### ISSUE TITLE
Gasverbruik

### ISSUE THREAD

**Issue by MichielioZ** [nldroid/CustomP1UartComponent#8]
Ik heb een tijdje ESPHome met jouw code gebruikt voor mijn slimme meter, maar ben door (toendertijd) problemen met de update frequentie van sensoren via ESPHome overgeschakeld op ESPEasy (wat trouwens lang niet zo "easy" was om werkend te krijgen).
Inmiddels lijkt het erop dat ESPHome bij m'n andere sensoren gewoon goed werkt en wil ik ook mijn Wemos D1 Mini weer terug naar ESPHome gaan flashen.
Eigenlijk vind ik het maar bij 2 waardes nuttig om regelmatig updates van te krijgen:
1) huidig stroomverbruik
2) gasverbruik per uur

Die laatste is in ESPEasy beschikbaar maar niet met jouw code.
Is het mogelijk om deze waarde ook met jouw code uit te lezen ?

**Comment by nldroid** [comment]
Ik denk dat de waarde per uur niet uit de meter komt naar dat hij berekend
wordt. Het is al een tijdje geleden dat ik naar de specs van het bericht
uit de meter gekeken heb maar volgens mij zit het er niet in.

Ik haal dat soort waarden uit de historie die in home assistant opgeslagen
worden.

Volgens mij heb je daar al coole charts in maar je kan ook los met grafana
of influxdb.

**Comment by MichielioZ** [comment]
Ah, helemaal niet aan gedacht dat je met metingen van het totale gasverbruik (die jij ook uitleest) en de tijd tussen metingen je een uurverbruik kunt genereren...
Standaard doet Home Assistant trouwens vrij weinig met de metingen van de (gas)meterstand, want dan is het gewoon een oplopende grafiek (voor eeuwig).
Als ik tijd hebt zal ik me eens in je code verdiepen en kijken of ik die waarde op de D1 Mini al kan berekenen (want dat geeft een nuttige grafiek in HA).

**Comment by dynasticorpheus** [comment]
@MichielioZ Kijk eens naar het onderstaande:

https://www.home-assistant.io/integrations/utility_meter/

**Comment by nldroid** [comment]
Dit gaat ook mogelijkheden geven: https://twitter.com/klaasnicolaas/status/1384584214402719746

**Comment by MichielioZ** [comment]
@dynasticorpheus & @nldroid : bedankt voor de suggesties.
Aankomend weekend heb ik wat tijd en ga ik kijken wat de beste oplossing is.
Het liefst doe ik eigenlijk alles op de D1 Mini, want behalve waardes doorgeven over Wifi zit die toch maar te niksen ;-)
In ieder geval goed om te weten dat ik opties heb om het eventueel anders aan te pakken...
